### ISSUE TITLE
Adding existing policy and/or group

### ISSUE THREAD

**Issue by Sangarshanan** [pycasbin/sqlalchemy-adapter#11]
Adding new policies. groups which already exist now inserts a duplicate is there any way to avoid that also will be nice if we can give out a warning in that case or maybe something like an `ignore_duplicate` flag

btw, Pycasbin has been really helpful in my projects, Cheers :v:

**Comment by hsluoyz** [comment]
@Sangarshanan can you make a PR?

**Comment by Sangarshanan** [comment]
Will do : )

**Comment by Sangarshanan** [comment]
Hello, just a quick update 

So I was trying actually trying to do `model.add_policy('g', 'g', ['alice', 'data1_admin'])`
but everytime I tried it, result was always `True` and I though the policies were being duplicated but it turns out it was only in the enforcer and not the storage since I did not run an adapter.save_policy, which actually saves it the DB and since the policies are deleted and replaced every time from the enforcer, there are actually no duplicates

I did not realise that the table was recreated and was under the assumption of an auto-save, Apologies for the confusion.

**Comment by hsluoyz** [comment]
@Sangarshanan can you fix this bug?

**Comment by Sangarshanan** [comment]
Oh there is no bug in this case, no duplicates are getting created since the table is recreated. I guess the issue can be safety closed
