### ISSUE TITLE
Support for policy subset loading

### ISSUE THREAD

**Issue by rituperiwal** [pycasbin/sqlalchemy-adapter#14]
I am using python and casbin_sqlalchemy_adapter adapter.
I see that file adapter has support for policy subset loading. Is it possible in casbin_sqlalchemy_adapter

**Comment by hsluoyz** [comment]
@techoner @Xhy-5000

**Comment by Xhy-5000** [comment]
I don't think that file adapter can load a subset of the policy... It seems that all the 'load_policy' methods in these adapters aim to load all the policies from the storage. Hope to be helpful, thanks.

**Comment by Xhy-5000** [comment]
Or you may try to use the 'load_policy_line' function directly to load a single policy in a text line. https://github.com/Xhy-5000/pycasbin/blob/master/casbin/persist/adapter.py

**Comment by rituperiwal** [comment]
Thanks for your reply @Xhy-5000. Actually, loading a single line will not solved my usecase.
We have hundreds of customers having unique id for each customer and each customer will have n number of users and against each user, there might be hundreds of policies saved in MySQL table for Casbin.
What I want to achieve by policy subset loading is that every time we validate permission for a user, we can limit the number of policies to be loaded by Adapter by the customer id to increase the performance like mentioned here - https://casbin.org/docs/en/policy-subset-loading

**Comment by wakemaster39** [comment]
I just opened #15 now implements this, support for this in upstream pycasbin was just recently merged.

https://github.com/casbin/pycasbin/pull/66

**Comment by hsluoyz** [comment]
@Xhy-5000 any update?

**Comment by Xhy-5000** [comment]
Nice, I have nothing additional.

**Comment by rituperiwal** [comment]
Hi @hsluoyz @Xhy-5000, is this update not merged yet? Please let me know once the MR is merged

**Comment by hsluoyz** [comment]
@techoner can you review the PR: https://github.com/pycasbin/sqlalchemy-adapter/pull/15 and merge it if it looks OK?

**Comment by rituperiwal** [comment]
In the updated adapter file, i see this error. Please suggest how to fix it
<img width="997" alt="Screenshot 2021-01-08 at 8 13 31 AM" src="https://user-images.githubusercontent.com/31469217/103968266-834a8300-5189-11eb-9c0e-680b55818437.png">

**Comment by hsluoyz** [comment]
@yyellowsun can you solve this?

**Comment by yyellowsun** [comment]
@rituperiwal,see [this](https://github.com/pycasbin/sqlalchemy-adapter/blob/59334bb5da78c1e5c5b621bef8f53dcbcdd36f65/casbin_sqlalchemy_adapter/adapter.py#L59),if db_class is None,it should be CasbinRule.There is no error in my IDE,I just see this 
![1610099339(1)](https://user-images.githubusercontent.com/44517408/104001008-f4dcfe00-5196-11eb-80e4-56cba6b4d4d0.jpg)
@wakemaster39 ,when I run the test file,[here](https://github.com/pycasbin/sqlalchemy-adapter/blob/59334bb5da78c1e5c5b621bef8f53dcbcdd36f65/casbin_sqlalchemy_adapter/adapter.py#L77),
TypeError: 'Filter' object is not iterable
filter.P is not iteratable,as you define[#L34](https://github.com/pycasbin/sqlalchemy-adapter/blob/59334bb5da78c1e5c5b621bef8f53dcbcdd36f65/casbin_sqlalchemy_adapter/adapter.py#L34)
![1610099339(1)](https://user-images.githubusercontent.com/44517408/104001864-2dc9a280-5198-11eb-8a1a-cc5baf2d4160.jpg)

@hsluoyz ,I think we should fix the bug and then update the PYPI.

**Comment by hsluoyz** [comment]
@yyellowsun can you make a PR to fix the bug? Thanks.

**Comment by rituperiwal** [comment]
> @rituperiwal,see [this](https://github.com/pycasbin/sqlalchemy-adapter/blob/59334bb5da78c1e5c5b621bef8f53dcbcdd36f65/casbin_sqlalchemy_adapter/adapter.py#L59),if db_class is None,it should be CasbinRule.There is no error in my IDE,I just see this
> ![1610099339(1)](https://user-images.githubusercontent.com/44517408/104001008-f4dcfe00-5196-11eb-80e4-56cba6b4d4d0.jpg)
> @wakemaster39 ,when I run the test file,[here](https://github.com/pycasbin/sqlalchemy-adapter/blob/59334bb5da78c1e5c5b621bef8f53dcbcdd36f65/casbin_sqlalchemy_adapter/adapter.py#L77),
> TypeError: 'Filter' object is not iterable
> filter.P is not iteratable,as you define[#L34](https://github.com/pycasbin/sqlalchemy-adapter/blob/59334bb5da78c1e5c5b621bef8f53dcbcdd36f65/casbin_sqlalchemy_adapter/adapter.py#L34)
> 
> @hsluoyz ,I think we should fix the bug and then update the PYPI.

Thanks! i think i copied the wrong file from the PR then. Will integrate the one you shared and let you know if i face any issue

**Comment by hsluoyz** [comment]
@rituperiwal @yyellowsun @wakemaster39 Some PRs are reverted to fix the Travic CI error. See my comment here: #15 (comment)

Sorry for this and we may need to have a new correct PR to add the filtered loading support.

@yyellowsun can you make a PR to add the filtered loading support?

/cc @techoner

**Comment by hsluoyz** [comment]
PR in progress: https://github.com/pycasbin/sqlalchemy-adapter/pull/24

**Comment by hsluoyz** [comment]
@rituperiwal PR merged.

@techoner can you plz make a new release on GitHub & pypi?

**Comment by hsluoyz** [comment]
@rituperiwal v0.2.0 released: https://github.com/pycasbin/sqlalchemy-adapter/releases/tag/v0.2.0

**Comment by rituperiwal** [comment]
Thank you so much!
