### ISSUE TITLE
self._db_class is used and never assigned a value

### ISSUE THREAD

**Issue by kickingbull** [pycasbin/sqlalchemy-adapter#17]
self._db_class is used in multiple locations but no where is it ever assigned a value.

**Comment by wakemaster39** [comment]
You are right, when I wrote the filter loader PR I didn't even think about the fact that #13 was still sitting in limbo. That PR resolve this as well as gives the ability to set your own class.

**Comment by kickingbull** [comment]
Thanks.  Hopefully the PR will get merged soon so the fix is in place.

**Comment by hsluoyz** [comment]
Waiting for @techoner to review & merge

**Comment by wakemaster39** [comment]
looks like this is merged now, should be good to go

**Comment by hsluoyz** [comment]
Can be closed. @techoner

**Comment by kickingbull** [comment]
Thanks

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/pycasbin/sqlalchemy-adapter/pull/13
