### ISSUE TITLE
New release (0.2.0?) with filter loading support

### ISSUE THREAD

**Issue by wakemaster39** [pycasbin/sqlalchemy-adapter#18]
With all the changes now merged for loading filtered policy, and the PRs merged upstream as well. Should make a new release so we don't need to use git references in pip.

**Comment by hsluoyz** [comment]
@techoner @Xhy-5000 please make a new release.

**Comment by techoner** [comment]
@wakemaster39  Travis CI build failed, can you fix it ?

**Comment by S4NT14G0** [comment]
Just took a look at your Travis CI builds and they appear to be failing due to the test throwing an error.  Any update when this will be fixed and a new version released?  Filters & db_class for the adapter would be nice to have.

**Comment by hsluoyz** [comment]
@S4NT14G0 Some PRs are reverted to fix the Travic CI error. See my comment here: https://github.com/pycasbin/sqlalchemy-adapter/pull/15#issuecomment-756764658

Sorry for this and we may need to have a new correct PR to add the filtered loading support.
