### ISSUE TITLE
Adapter _save_policy_line only writes to v0 for all rule fields

### ISSUE THREAD

**Issue by bburrier** [pycasbin/sqlalchemy-adapter#2]
https://github.com/pycasbin/sqlalchemy-adapter/blob/aa7b1f52e6ce3e1eb2ce95caef0e9f5a97db17d6/casbin_sqlalchemy_adapter/adapter.py#L54-L70

When I pass in a rule the only value that gets written to the database is the last value field of the rule and this always gets written into v0 as it is the only column referenced in each case. 

The column for each case should be updated to match the rule field index, `line.v1 = rule[1]`, etc.

**Comment by hsluoyz** [comment]
Hi @bburrier , we have a PR in progress to solve this issue: https://github.com/pycasbin/sqlalchemy-adapter/pull/1  When it's merged, we will release a new version and let you know.

**Comment by techoner** [comment]
@bburrier It has been resolved in the new version.
