### ISSUE TITLE
Connect to MSSQL db on Azure

### ISSUE THREAD

**Issue by msdcanderson** [pycasbin/sqlalchemy-adapter#20]
Hi,

What would the connection look like for connecting to an MSSQL DB on Azure?

Thank you

**Comment by hsluoyz** [comment]
@yyellowsun

**Comment by hsluoyz** [comment]
@msdcanderson see: https://docs.sqlalchemy.org/en/13/dialects/mssql.html#dialect-mssql-pyodbc-connect

![image](https://user-images.githubusercontent.com/3787410/99029524-a4d62680-25ad-11eb-9681-2a70909bb616.png)

**Comment by msdcanderson** [comment]
That's great - thank you @hsluoyz
