### ISSUE TITLE
fix inconsistent schema

### ISSUE THREAD

**Issue by viglia** [pycasbin/sqlalchemy-adapter#25]
Trying to use the python's `casbin_sqlalchemy_adapte` to access a Casbin policy stored on Postgres with Golang's `sql-adapter` return the following error:

```psycopg2.errors.UndefinedColumn: column casbin_rule.id does not exist
LINE 1: SELECT casbin_rule.id AS casbin_rule_id, casbin_rule.ptype A...```

This is due to the fact that the Golang's sql adapter does not add an `id` column which is actually required for the Python adapter.

The schema should be made consistent in order to allow interoperability of the same Casbin rule system/table across different languages.

**Comment by hsluoyz** [comment]
@viglia which Go adapter do you use? Can you provide a link?

**Comment by viglia** [comment]
Sure. This is the adapter I'm using: https://github.com/Blank-Xu/sql-adapter

**Comment by hsluoyz** [comment]
@viglia that's a 3rd-party adapter. Can you create an issue about this problem at that repo?

**Comment by viglia** [comment]
ok, right. Ignore this then

**Comment by hsluoyz** [comment]
@viglia we recommend using the official adapters like Xorm adapter or Gorm adapter, which has more features. But if you decide to use: https://github.com/Blank-Xu/sql-adapter , plz also send issue at: https://github.com/Blank-Xu/sql-adapter , we may make a PR at that repo too to solve your problem.
