### ISSUE TITLE
Inconsistent schema with Original Gorm adapter

### ISSUE THREAD

**Issue by viglia** [pycasbin/sqlalchemy-adapter#26]
Hi, 

I've opened a similar ticket yesterday but this time it's about an inconsistency between the `pycasbin/sqlalchemy-adapter` and the `casbin/gorm-adapter`

When the casbin Rule Table is created through the gorm adapter, the 1st column is named `p_type`.

When the same Table is created by SQLAlchemy, the 1st column is named `ptype`. 

This creates interoperability issues.

This could either be fixed in the Gorm Adaper by changing the name (see [here](https://gorm.io/docs/conventions.html#Column-Name)) or in the SQLAlchemy adapter.

Let me know if you need some help with this.

Thank you

**Comment by hsluoyz** [comment]
Hi @viglia , after community discussion, we think maybe using `ptype` uniformly for all Casbin adapters would be better, as`p_type` is error-prone.

Actually I determined the name `p_type` at first in several Go adapters. But after several years, it has gradually become `ptype` in other implementations and other adapters. So maybe we should directly use `ptype` to avoid any further ambiguities.

**Comment by hsluoyz** [comment]
@viglia resolved: https://github.com/casbin/gorm-adapter/issues/67
