### ISSUE TITLE
[BUG] Missing guard clause?

### ISSUE THREAD

**Issue by filwaline** [pycasbin/sqlalchemy-adapter#27]
https://github.com/pycasbin/sqlalchemy-adapter/blob/2118a94eaa049ff1b6d3325c3999b5b1a50c81e7/casbin_sqlalchemy_adapter/adapter.py#L112-L124

[Policy Subset Loading](https://casbin.org/docs/en/policy-subset-loading) mention that `SavePolicy` should disable while apply subset loading.

**Comment by hsluoyz** [comment]
That restriction code inside the main lib - PyCasbin instead of specific adapters:

https://github.com/casbin/pycasbin/blob/5676034a91c93c08a7f1ee42686448a0aa852434/casbin/core_enforcer.py#L179-L186

```py
    def save_policy(self):
        if self.is_filtered():
            raise RuntimeError("cannot save a filtered policy")

        self.adapter.save_policy(self.model)

        if self.watcher:
            self.watcher.update()
```
