### ISSUE TITLE
How to use postgresql db?

### ISSUE THREAD

**Issue by Ray-Lei-93** [pycasbin/sqlalchemy-adapter#28]
I see the example and the issue about mysql db, but still confused. Can you give me any clue how I can connect to my postgresql db?

**Comment by hsluoyz** [comment]
@Ray-Lei-93 it directly uses sqlalchemy's connecting string:

https://github.com/pycasbin/sqlalchemy-adapter/blob/2118a94eaa049ff1b6d3325c3999b5b1a50c81e7/casbin_sqlalchemy_adapter/adapter.py#L44-L57

See: https://docs.sqlalchemy.org/en/14/core/engines.html#postgresql

```py
# default
engine = create_engine('postgresql://scott:tiger@localhost/mydatabase')

# psycopg2
engine = create_engine('postgresql+psycopg2://scott:tiger@localhost/mydatabase')

# pg8000
engine = create_engine('postgresql+pg8000://scott:tiger@localhost/mydatabase')
```

**Comment by Ray-Lei-93** [comment]
Now I understand! :) Thanks for your reply.
