### ISSUE TITLE
How should I use batch operations？ it seems that there is no “add_policies” method

### ISSUE THREAD

**Issue by zxj17815** [pycasbin/sqlalchemy-adapter#33]
What should I do if I implement it myself

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
Are you trying to use transactions?

**Comment by Zxilly** [comment]
Sometimes we take batch operations in a transaction. Sometimes it just for convenience.
Which one do you perfer?

**Comment by hsluoyz** [comment]
@Zxilly  I think we can implement `add_policies()` API in a single SQL execution. So this will be atomic and inside a transaction. Can you implement the `add_policies()` API?

**Comment by Zxilly** [comment]
@hsluoyz I'm not familiar with sqlalchemy. This will take extra time.
Anyone else can work on this?

**Comment by wakemaster39** [comment]
Pushed up a PR that should add this feature.

As an aside, if you also set the adapter to have commit as False, and control the session externally (you should really do this anyways in my opinion) you will be able to have rollback support across multiple actions and in sync with your greater database transaction as a whole.

**Comment by hsluoyz** [comment]
@Zxilly plz make a new release.

**Comment by hsluoyz** [comment]
@techoner plz release on commit: https://github.com/pycasbin/sqlalchemy-adapter/commit/218b193dca68d94c6ad665b85790fc32e30761c8

**Comment by hsluoyz** [comment]
@zxj17815 released: https://github.com/pycasbin/sqlalchemy-adapter/releases/tag/v0.3.1

**Comment by zxj17815** [comment]
@hsluoyz It worked, thank you for solving my problem
