### ISSUE TITLE
possibly wrong behavior for `remove_policies`

### ISSUE THREAD

**Issue by sunhs** [pycasbin/sqlalchemy-adapter#38]
Assume I have the following policies:

```
p, developer, domain, obj1, write
p, guest, domain, obj2, read
g, user, developer, domain
```

And I remove one of the policy using

```python
policies_for_obj = enforcer.get_filtered_policy(2, "obj1")  # This returns ['developer', 'domain', 'obj1', 'write']
enforcer.remove_policies(policies_for_obj)
```

Then all the policies are deleted.

In [these lines](https://github.com/pycasbin/sqlalchemy-adapter/blob/master/casbin_sqlalchemy_adapter/adapter.py#L159-L160),

https://github.com/pycasbin/sqlalchemy-adapter/blob/602cfd61c74e9dacdf0d25ea1209563d4c924a14/casbin_sqlalchemy_adapter/adapter.py#L159-L160

the `or_` will translate the filter into something like:

`v0==developer or v1==domain or v2==obj1 or v3==write`

and all the policies will match this filter since `v1==domain` holds for all of them.

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by hsluoyz** [comment]
@techoner plz make a new release.
