### ISSUE TITLE
The CI failed to release new package to pypi owing to 403 error

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/sqlalchemy-adapter#42]
See how we did it for other repos.

**Comment by hsluoyz** [comment]
@ffyuanda finish this before: https://github.com/pycasbin/sqlalchemy-adapter/issues/41

**Comment by ffyuanda** [comment]
working on this

**Comment by hsluoyz** [comment]
The CI failed to release new package to pypi: https://github.com/pycasbin/sqlalchemy-adapter/runs/3091504979?check_suite_focus=true

@techoner can you help fix this?

![image](https://user-images.githubusercontent.com/3787410/126025475-9b06d2c1-3e5f-4cb6-9bcf-281ccfd4205d.png)

**Comment by techoner** [comment]
Fixed.
