### ISSUE TITLE
Fix the download badge

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/sqlalchemy-adapter#46]
Some other repos like https://github.com/pycasbin/postgresql-watcher also have this issue:

![image](https://user-images.githubusercontent.com/3787410/126055102-3e5d1090-1d72-4dbd-a00d-7504492f6351.png)

**Comment by hsluoyz** [comment]
@Zxilly @ffyuanda

**Comment by techoner** [comment]
It recovers on its own .
