### ISSUE TITLE
how to use custom sqlalchemy model

### ISSUE THREAD

**Issue by derekn** [pycasbin/sqlalchemy-adapter#50]
so far I've been unsuccessful in trying to use a custom model in place of CasbinRule. is this possible?

importing Base and adding a model to that still tries to create the casbin_rule table from CasbinRule

**Comment by hsluoyz** [comment]
@Zxilly @ffyuanda @techoner

**Comment by Zxilly** [comment]
Have you tried `migrate`?

**Comment by derekn** [comment]
No, can you elaborate or link to docs?

**Comment by Zxilly** [comment]
@derekn https://sqlalchemy-migrate.readthedocs.io/en/latest/

**Comment by derekn** [comment]
I think my question was misunderstood, let me clarify... I'm trying to use a custom database model other than the default CasbinRule, not a database migration. I see that Adapter init provides a `db_class` param, but when passing my own model class, it gets ignored and still tries to use CasbinRule and create a casbin_rule table when instantiated.

it appears this is because CasbinRule inherits from declarative_base and is already part of the metadata when create_all is called

**Comment by w-Bro** [comment]
my question is same with you, have you solve this question? @derekn

**Comment by derekn** [comment]
> my question is same with you, have you solve this question? @derekn

no, still waiting for a reply, but I think it will require a code change as it seems like a bug that the db_class is ignored

**Comment by Zxilly** [comment]
Working on this

**Comment by derekn** [comment]
confirmed the pr fixes the issue

**Comment by derekn** [comment]
found one more related issue... the `filter_query` method is using hard-coded CasbinRule model, it should be updated to use `self.db_class` instead.

should I create a new issue or is this enough?

**Comment by Zxilly** [comment]
@derekn I will keep a constant follow-up.
@hsluoyz plz reopen this issue.

**Comment by derekn** [comment]
works perfectly, thanks guys!
