### ISSUE TITLE
Implement update_filtered_policies()

### ISSUE THREAD

**Issue by leeqvip** [pycasbin/sqlalchemy-adapter#53]
@ffyuanda

**Comment by ffyuanda** [comment]
Will do in this week.

**Comment by Shivansh-yadav13** [comment]
@leeqvip can I contribute to this?

**Comment by hsluoyz** [comment]
Sure

**Comment by Shivansh-yadav13** [comment]
Hello, I wanted to ask that `sec` is not used anywhere inside the `update_policy()` should it be removed? https://github.com/pycasbin/sqlalchemy-adapter/blob/2222d9affeffde19dbd16bc0d06a30511d743f05/casbin_sqlalchemy_adapter/adapter.py#L194

**Comment by Shivansh-yadav13** [comment]
@hsluoyz we would also have to add `update_filtered_policies` in the management API pycasbin

**Comment by leeqvip** [comment]
> @hsluoyz we would also have to add `update_filtered_policies` in the management API pycasbin

Yes, waiting for your PR.

**Comment by Shivansh-yadav13** [comment]
@leeqvip are we not going to add update_filtered_policies method here?
