### ISSUE TITLE
Implement has_policy() method to check whether the policy exists before adding the policy

### ISSUE THREAD

**Issue by kirankumargmrur** [pycasbin/sqlalchemy-adapter#54]
Hi,

Currently, there is no function to verify whether a policy already exists in the database. Hence, the adapter is allowing to create duplicate entries in the table whenever you re-run the script.
![image](https://user-images.githubusercontent.com/35611028/152285424-122b441e-e1a3-4ed1-8baa-acdcc72d9f9a.png)
```
def add_policy(self, sec, ptype, rule):
        """adds a policy rule to the storage."""
        self._save_policy_line(ptype, rule)
```
I guess, the above method didn't check for existing entries in the table, hence the issue might be occuring.

**Code to reproduce:**
Run the below code snippet for 5-6 times and in database you found those many entries of same policy.

```
import casbin_sqlalchemy_adapter
import casbin

adapter = casbin_sqlalchemy_adapter.Adapter('sqlite:///test.db')

e = casbin.Enforcer('path/to/model.conf', adapter, True)
e.add_policy('admin', 'domain1', 'data1', 'read')
print(e.get_policy())
```

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@kirankumargmrur  Judging whether the strategy exists, it has been implemented in pycasbin(https://github.com/casbin/pycasbin/blob/master/casbin/model/policy.py#L101), probably there is a bug .
What is the content of your `model.conf` ?

**Comment by kirankumargmrur** [comment]
Hey @leeqvip thanks for the response, my model.conf is very basic
```

   
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act
```

Yeah! I saw it was implemented in pycasbin. It works fantastic when we don't use the database adapter. But when we use this adapter, there is  add_policy() method (https://github.com/pycasbin/sqlalchemy-adapter/blob/2222d9affeffde19dbd16bc0d06a30511d743f05/casbin_sqlalchemy_adapter/adapter.py#L140) in the adapter itself, I suspect because of which issue might be occuring, as enforcer will use this method to add policy into the database.

Thanks

**Comment by leeqvip** [comment]
```python
    adapter = casbin_sqlalchemy_adapter.Adapter('sqlite:///test.db')

    e = casbin.Enforcer('model.conf', adapter)

    res = e.add_policy('admin', 'domain1', 'data1', 'read')
    print(res)  # True
    print(e.get_policy()) # [['admin', 'domain1', 'data1', 'read']]

    res = e.add_policy('admin', 'domain1', 'data1', 'read')
    print(res) # False
    print(e.get_policy()) # [['admin', 'domain1', 'data1', 'read']]
```
![image](https://user-images.githubusercontent.com/35752209/153609663-934453cf-445e-40e2-a557-5891bacdc12d.png)

@kirankumargmrur Through the above code, no problem was found. 
```
casbin                    1.15.4
casbin-sqlalchemy-adapter 0.4.2
```

**Comment by kirankumargmrur** [comment]
@leeqvip As I mentioned in the issue, Don't add policy twice in the same thread. Save this file as test.py or something and then run it twice or thrice. 
Basically you need to call "python test.py", more than once

**Comment by leeqvip** [comment]
@kirankumargmrur 
If it is a single Enforcer instance, then in multi-threaded add_policy, we need to use [SyncedEnforcer](https://github.com/casbin/pycasbin/blob/master/casbin/synced_enforcer.py#L38);
If it is multiple Enforcer instances or distributed, we need to use [watcher](https://casbin.org/docs/en/watchers) to synchronize policies in different instances.

**Comment by kirankumargmrur** [comment]
Hi @leeqvip got it. I will try it out SyncedEnforcer. But I have one more question,
Here is the scenario, how this solution scales horizontally (I am aware one solution is watchers or loading policies before validating the policy). Is there any other solution?

**Comment by leeqvip** [comment]
@kirankumargmrur  Casbin's policies is to load all into memory during initialization, and does not need to load the policy every time, so currently in the multi-instance scenario, `Watcher` is a better choice.

**Comment by hsluoyz** [comment]
Closed as resolved
