### ISSUE TITLE
RBAC with domain does not work with SQL Alchemy Adapter

### ISSUE THREAD

**Issue by LucasHartridge** [pycasbin/sqlalchemy-adapter#61]
Hey team :wave: happy new year :tada: 

I have been debugging and testing different GitHub issues that were opened in the past, and looking through the documentation but I was not able to make work Py Casbin with RBAC with the domains model

I have the same conf that in the official documentation https://casbin.org/docs/rbac-with-domains. The only difference is that instead of using a CSV file I am using the SQL Alchemy Adapter

Looking through the unit test, I only found coverage for simple RBAC with sub, obj, and action and I believe that is the main reason the Enforcer is not returning True when it should because it is not implemented in the Adapter. Can you confirm this?

I have tested my configuration in the casbin online editor and the enforcer returns True

![image](https://user-images.githubusercontent.com/8227333/210154003-327ad01e-f598-4ade-9c34-695bb01834a9.png)

I saw that Pycasbin used to have an issue related RBAC with domain but was fixed here https://github.com/casbin/pycasbin/pull/92

I found in the issue that I shared that the domain matching func should be added like this

```
  enforcer = Enforcer("rbac-tenant.conf", Adapter(engine=settings.DATABASE_URL, db_class=RBAC))
  enforcer.add_named_domain_matching_func("g", key_match2)
  result = enforcer.enforce(user_id, organization_id, self.obj, self.action)
```

Also tried without adding it and many others but the Enforcer always return false

By the way, the connection with the Adapter is working perfectly because when I create an Organization Owner user, I am adding the policies and the group, and works totally fine

```
enforcer = Enforcer("rbac-tenant.conf", Adapter(engine=settings.DATABASE_URL, db_class=RBAC))
enforcer.add_role_for_user_in_domain(str(user_id), "ORGANIZATION_OWNER", str(organization_id))
enforcer.add_policy("ORGANIZATION_OWNER", str(organization_id), "organizations", "update")
enforcer.add_policy("ORGANIZATION_OWNER", str(organization_id), "organizations", "delete")
enforcer.add_policy("ORGANIZATION_OWNER", str(organization_id), "organizations", "read")
```

Thanks for the help

**Comment by terry-xuan-gao** [comment]
Hello, I'm trying to solve this issue, but I can't reproduce the problem you encountered, and here is my code, it seems to work fine.

- test.py

```python
import os

import casbin
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import sessionmaker

from casbin_sqlalchemy_adapter import Adapter
from casbin_sqlalchemy_adapter import Base
from casbin_sqlalchemy_adapter import CasbinRule


def get_fixture(path):
    dir_path = os.path.split(os.path.realpath(__file__))[0] + "/"
    return os.path.abspath(dir_path + path)


def get_enforcer():
    engine = create_engine("sqlite:///downloads/test.db", echo=True)

    adapter = Adapter(engine)

    session = sessionmaker(bind=engine)
    Base.metadata.create_all(engine)
    s = session()
    s.query(CasbinRule).delete()
    s.add(CasbinRule(ptype="p", v0="ORGANIZATION_OWNER", v1="2", v2="organizations", v3="read" ))
    s.add(CasbinRule(ptype="p", v0="ORGANIZATION_OWNER", v1="2", v2="organizations", v3="write" ))
    s.add(CasbinRule(ptype="p", v0="ORGANIZATION_OWNER", v1="2", v2="organizations", v3="delete"))

    s.add(CasbinRule(ptype="g", v0="1", v1="ORGANIZATION_OWNER", v2="2"))

    s.commit()
    s.close()

    return casbin.Enforcer(get_fixture("rbac_with_domains_model.conf"), adapter)


e = get_enforcer()

res1 = e.enforce("1", "2", "organizations", "read")
res2 = e.enforce("1", "2", "organizations", "write")
res3 = e.enforce("1", "2", "organizations", "delete")

print(res1, res2, res3)

```

- output

```
True True True
```

![ZFR J VKB{SAL E`%P}NRUD](https://user-images.githubusercontent.com/84124955/218774521-9782735d-4d2c-4a43-b581-4480ff1cad2a.png)




The policy in this case is constructed according to the content in the picture you gave, I understand you got `False` in this case, but I do get `True`.

If I misunderstood your issue you can let me know and I'll be happy to help : )

**Comment by LucasHartridge** [comment]
@terry-xuan-gao Thank you very much for taking the time to reply to me. Sorry I could not ping you before I was disconnected from work :face_with_head_bandage: 

You understood correctly!. Each time I call the enforce and it returns False instead of True. Also If I switch the adapter to you the CSV the code works fine too, returning True on the enforce

As you said your code works fine. I agree with you that it can be a DB problem. I am using Postgres SQL, in concrete postgres:14.5-alpine

Let me know if I can help give more details 

Thanks again for your time!

**Comment by hsluoyz** [comment]
@LucasHartridge Casbin enforcer will return the same enforcement result for the same model and policy, no matter what adapter is used. Please:

1. Show your `casbin_rule` table in your DB
2. Show `get_policy()` and `get_grouping_policy()` results
3. Provide a full example of code (better to be a github repo) to reproduce the issue

**Comment by hsluoyz** [comment]
Closed as stale.
