### ISSUE TITLE
Readme has 3rd parameter as True which causes TypError: __init__() takes from 1 to 3 positional arguments but 3 were given

### ISSUE THREAD

**Issue by erenz14** [pycasbin/sqlalchemy-adapter#62]
Readme has enforcer being initialized with the following line: `e = casbin.Enforcer('path/to/model.conf', adapter, True)`

BUT, CoreEnforcer init only has the following params: `def __init__(self, model=None, adapter=None)`

I get the following error when I leave the 3rd param as True: `TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given`

If this is confirmed as a bug in the readme, please lmk if I can help to make the change as it would be my first 😄

**Comment by hsluoyz** [comment]
Removed
