### ISSUE TITLE
ABAC   RuntimeError("invalid policy size")

### ISSUE THREAD

**Issue by Castle1984** [pycasbin/sqlalchemy-adapter#64]
I want to use ABAC.
![image](https://github.com/pycasbin/sqlalchemy-adapter/assets/48825393/fd08ac64-4647-4add-b95d-ef7730b80ebf)

Here is the problem.
![image](https://github.com/pycasbin/sqlalchemy-adapter/assets/48825393/54b5a6c1-5213-49b7-af33-c63755d033cb)

The rule has been written in Mysql.
![image](https://github.com/pycasbin/sqlalchemy-adapter/assets/48825393/047d7673-5dd4-4438-a469-8da73ce769fa)

The model.conf :
![image](https://github.com/pycasbin/sqlalchemy-adapter/assets/48825393/02431a29-1e7d-473d-998d-82401b1c1ea1)

So how could I express Age=30?

**Comment by hsluoyz** [comment]
@Castle1984 remove this extra `p`:

![image](https://github.com/pycasbin/sqlalchemy-adapter/assets/3787410/d8c3c30e-76cd-43c0-9a78-8ee8111ad35c)
