### ISSUE TITLE
save_policy doesn't work as describe in document

### ISSUE THREAD

**Issue by shizidushu** [pycasbin/sqlalchemy-adapter#7]
The [docuemnt](https://casbin.org/docs/en/adapters#autosave) says:
> This is unlike SavePolicy(), because the latter will delete all policy rules in the storage and save all policy rules from Casbin enforcer to the storage. 

```python
import casbin_sqlalchemy_adapter
import casbin


adapter = casbin_sqlalchemy_adapter.Adapter('sqlite:///test.db')

report_paths = [{'path': '/api/v1/report/product/ungrouped/items/', 'method': 'get', 'tags': 'report_product_ungrouped'}, {'path': '/api/v1/report/product/ungrouped/items2/', 'method': 'get', 'tags': 'report_product_ungrouped'}]

e = casbin.Enforcer('C:\\Users\\username\\Documents\\scripts\\myproject\\app\\casbin_model.conf', adapter, True)
e.enable_auto_save(False)

e.add_policy('alice', 'data5', 'read')

e.save_policy()
e.save_policy()
```

When I run the above code, it just save another record of the same policy to database.

**Comment by hsluoyz** [comment]
@techoner , `save_policy()` should delete all policy rules at first.

https://github.com/pycasbin/sqlalchemy-adapter/blob/master/casbin_sqlalchemy_adapter/adapter.py#L61-L69

See Golang's Xorm adapter as a reference:

https://github.com/casbin/xorm-adapter/blob/26747826035016c67ef5a381263da206504f959a/adapter.go#L250-L279

Can we fix it?
