### ISSUE TITLE
Race condition results in multiple identical rules

### ISSUE THREAD

**Issue by yenchenLiu** [pycasbin/sqlalchemy-adapter#73]
I have multiple servers, and sometimes multiple Rules are inserted. Once the server has multiple identical Rules, the Rule will not be deleted.

My current solution is to check whether the rules are duplicated every time I read or store the rules and need to rewrite them and filter them out through set[tuple[rule0, rule1,...]]. 

But I would like to ask if this Library also wants to implement this method.

**Comment by hsluoyz** [comment]
@yenchenLiu it has nothing to do with this adapter. Wrong place to ask. Closed here.
